// Universities-Voice - Static data for the 18 Jordanian universities

export interface UniversityInfo {
  slug: string;
  name_ar: string;
  name_en: string;
  city_ar: string;
  city_en: string;
  founded: number;
  website: string;
  type: 'public' | 'private';
  description_ar: string;
  description_en: string;
}

export const UNIVERSITIES_DATA: UniversityInfo[] = [
  {
    slug: 'university-of-jordan',
    name_ar: 'جامعة الأردن',
    name_en: 'University of Jordan',
    city_ar: 'عمّان',
    city_en: 'Amman',
    founded: 1962,
    website: 'https://ju.edu.jo',
    type: 'public',
    description_ar: 'أقدم وأكبر جامعة في الأردن، وتعد من أبرز مؤسسات التعليم العالي في المنطقة.',
    description_en: 'The oldest and largest university in Jordan, and one of the most prominent higher education institutions in the region.',
  },
  {
    slug: 'just',
    name_ar: 'جامعة العلوم والتكنولوجيا',
    name_en: 'Jordan University of Science and Technology (JUST)',
    city_ar: 'إربد',
    city_en: 'Irbid',
    founded: 1986,
    website: 'https://just.edu.jo',
    type: 'public',
    description_ar: 'جامعة رائدة في مجالات العلوم والهندسة والطب في الأردن والمنطقة.',
    description_en: 'A leading university in science, engineering, and medicine in Jordan and the region.',
  },
  {
    slug: 'hashemite-university',
    name_ar: 'الجامعة الهاشمية',
    name_en: 'Hashemite University',
    city_ar: 'الزرقاء',
    city_en: 'Zarqa',
    founded: 1995,
    website: 'https://hu.edu.jo',
    type: 'public',
    description_ar: 'جامعة حكومية حديثة تتميز بحرمها الجامعي الواسع وبرامجها المتنوعة.',
    description_en: 'A modern public university known for its expansive campus and diverse programs.',
  },
  {
    slug: 'yarmouk-university',
    name_ar: 'جامعة اليرموك',
    name_en: 'Yarmouk University',
    city_ar: 'إربد',
    city_en: 'Irbid',
    founded: 1976,
    website: 'https://yu.edu.jo',
    type: 'public',
    description_ar: 'من أعرق الجامعات الأردنية، تشتهر بكلياتها الإنسانية والعلمية.',
    description_en: 'One of the most established Jordanian universities, renowned for its humanities and science faculties.',
  },
  {
    slug: 'al-balqa-applied',
    name_ar: 'البلقاء التطبيقية',
    name_en: 'Al-Balqa Applied University',
    city_ar: 'السلط',
    city_en: 'Salt',
    founded: 1997,
    website: 'https://bau.edu.jo',
    type: 'public',
    description_ar: 'جامعة حكومية متخصصة في التعليم التطبيقي والتقني بفروع منتشرة في المملكة.',
    description_en: 'A public university specializing in applied and technical education with branches across the kingdom.',
  },
  {
    slug: 'mutah-university',
    name_ar: 'جامعة مؤتة',
    name_en: 'Mutah University',
    city_ar: 'الكرك',
    city_en: 'Karak',
    founded: 1981,
    website: 'https://mutah.edu.jo',
    type: 'public',
    description_ar: 'جامعة حكومية في جنوب الأردن تضم جناحين مدنياً وعسكرياً.',
    description_en: 'A public university in southern Jordan with both civilian and military wings.',
  },
  {
    slug: 'al-ahliyya-amman',
    name_ar: 'جامعة عمّان الأهلية',
    name_en: 'Al-Ahliyya Amman University',
    city_ar: 'عمّان',
    city_en: 'Amman',
    founded: 1990,
    website: 'https://ammanu.edu.jo',
    type: 'private',
    description_ar: 'أول جامعة خاصة في الأردن، تقدم برامج متنوعة في مختلف التخصصات.',
    description_en: 'The first private university in Jordan, offering diverse programs across many disciplines.',
  },
  {
    slug: 'middle-east-university',
    name_ar: 'جامعة الشرق الأوسط',
    name_en: 'Middle East University',
    city_ar: 'عمّان',
    city_en: 'Amman',
    founded: 2005,
    website: 'https://meu.edu.jo',
    type: 'private',
    description_ar: 'جامعة خاصة تركز على الدراسات العليا والبرامج المهنية الحديثة.',
    description_en: 'A private university focusing on graduate studies and modern professional programs.',
  },
  {
    slug: 'german-jordanian',
    name_ar: 'الجامعة الألمانية الأردنية',
    name_en: 'German Jordanian University',
    city_ar: 'عمّان',
    city_en: 'Amman',
    founded: 2005,
    website: 'https://gju.edu.jo',
    type: 'public',
    description_ar: 'جامعة حكومية تعتمد النموذج الألماني في التعليم التطبيقي وتوفر سنة دراسية في ألمانيا.',
    description_en: 'A public university following the German applied-sciences model, including a study year in Germany.',
  },
  {
    slug: 'jerash-university',
    name_ar: 'جامعة جرش',
    name_en: 'Jerash University',
    city_ar: 'جرش',
    city_en: 'Jerash',
    founded: 1993,
    website: 'https://jpu.edu.jo',
    type: 'private',
    description_ar: 'جامعة خاصة في مدينة جرش التاريخية تقدم برامج متعددة التخصصات.',
    description_en: 'A private university in the historic city of Jerash offering multidisciplinary programs.',
  },
  {
    slug: 'philadelphia-university',
    name_ar: 'جامعة فيلادلفيا',
    name_en: 'Philadelphia University',
    city_ar: 'عمّان',
    city_en: 'Amman',
    founded: 1989,
    website: 'https://philadelphia.edu.jo',
    type: 'private',
    description_ar: 'جامعة خاصة معروفة ببرامجها في تكنولوجيا المعلومات والهندسة والآداب.',
    description_en: 'A private university known for its IT, engineering, and arts programs.',
  },
  {
    slug: 'amman-arab-university',
    name_ar: 'جامعة عمّان العربية',
    name_en: 'Amman Arab University',
    city_ar: 'عمّان',
    city_en: 'Amman',
    founded: 1997,
    website: 'https://aau.edu.jo',
    type: 'private',
    description_ar: 'جامعة خاصة بدأت بالدراسات العليا وتوسعت لتشمل برامج البكالوريوس.',
    description_en: 'A private university that began with graduate studies and expanded into undergraduate programs.',
  },
  {
    slug: 'psut',
    name_ar: 'جامعة الأميرة سمية للتكنولوجيا',
    name_en: 'Princess Sumaya University for Technology',
    city_ar: 'عمّان',
    city_en: 'Amman',
    founded: 1991,
    website: 'https://psut.edu.jo',
    type: 'private',
    description_ar: 'جامعة متخصصة في تكنولوجيا المعلومات والاتصالات وريادة الأعمال.',
    description_en: 'A university specializing in information technology, communications, and entrepreneurship.',
  },
  {
    slug: 'isra-university',
    name_ar: 'جامعة إسراء',
    name_en: 'Isra University',
    city_ar: 'عمّان',
    city_en: 'Amman',
    founded: 1991,
    website: 'https://iu.edu.jo',
    type: 'private',
    description_ar: 'جامعة خاصة تقدم برامج في الهندسة والصيدلة والعلوم الإدارية.',
    description_en: 'A private university offering programs in engineering, pharmacy, and administrative sciences.',
  },
  {
    slug: 'petra-university',
    name_ar: 'جامعة البترا',
    name_en: 'Petra University',
    city_ar: 'عمّان',
    city_en: 'Amman',
    founded: 1991,
    website: 'https://uop.edu.jo',
    type: 'private',
    description_ar: 'جامعة خاصة معروفة ببرامجها في الصيدلة والإعلام واللغات.',
    description_en: 'A private university known for its pharmacy, media, and languages programs.',
  },
  {
    slug: 'applied-science-university',
    name_ar: 'جامعة العلوم التطبيقية',
    name_en: 'Applied Science University',
    city_ar: 'عمّان',
    city_en: 'Amman',
    founded: 1991,
    website: 'https://asu.edu.jo',
    type: 'private',
    description_ar: 'من أوائل الجامعات الخاصة في الأردن، تضم كليات علمية وإنسانية متنوعة.',
    description_en: 'One of the earliest private universities in Jordan, with diverse scientific and humanities faculties.',
  },
  {
    slug: 'aqaba-university',
    name_ar: 'جامعة أقابة',
    name_en: 'Aqaba University',
    city_ar: 'العقبة',
    city_en: 'Aqaba',
    founded: 2015,
    website: 'https://aut.edu.jo',
    type: 'private',
    description_ar: 'جامعة حديثة في مدينة العقبة تركز على التكنولوجيا والعلوم البحرية والسياحة.',
    description_en: 'A modern university in Aqaba focusing on technology, marine sciences, and tourism.',
  },
  {
    slug: 'al-zaytoonah',
    name_ar: 'جامعة الزيتونة',
    name_en: 'Al-Zaytoonah University',
    city_ar: 'عمّان',
    city_en: 'Amman',
    founded: 1993,
    website: 'https://zuj.edu.jo',
    type: 'private',
    description_ar: 'جامعة خاصة تقدم برامج في تكنولوجيا المعلومات والتمريض والهندسة.',
    description_en: 'A private university offering programs in IT, nursing, and engineering.',
  },
];

export function getUniversityBySlug(slug: string): UniversityInfo | undefined {
  return UNIVERSITIES_DATA.find((u) => u.slug === slug);
}
